/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petugas;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Fachmi Farizh
 */
public class backupdata extends javax.swing.JFrame {

    /**
     * Creates new form backupdata
     */
    public backupdata() {
        initComponents();
        backupDatabase();
    }
    
    //set backup
    public void backupDatabase(){
        Date tgl_backup = new Date();
        String format_tgl_backup = "ddMMyyyyHHmmss";
        SimpleDateFormat fm_tgl_backup = new SimpleDateFormat(format_tgl_backup);
        String tanggal_backup = String.valueOf(fm_tgl_backup.format(tgl_backup));
        txt_nama_db.setText("db_spp");
        txt_lokasi_db.setText("C:\\backup_db\\");
        txt_nama_file.setText("db_spp" + tanggal_backup);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserLokasiFile = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_lokasi_db = new javax.swing.JTextField();
        txt_nama_db = new javax.swing.JTextField();
        txt_nama_file = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnPilih = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnBackup = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NAMA DATABASE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 130, 40));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("LOKASI FILE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 130, 50));

        jLabel4.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(".SQL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 30, 50));
        getContentPane().add(txt_lokasi_db, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 200, 50));
        getContentPane().add(txt_nama_db, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 200, 50));
        getContentPane().add(txt_nama_file, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 200, 50));

        jLabel5.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel5.setText("NAMA FILE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 360, 120, 50));

        btnPilih.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnPilih.setText("CARI");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });
        getContentPane().add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 70, 50));

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(".SQL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 40, 50));

        btnBackup.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        btnBackup.setText("CADANGKAN");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });
        getContentPane().add(btnBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ikon/close.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/backup.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
    FileNameExtensionFilter filter = new FileNameExtensionFilter("sql file", "sql");
        fileChooserLokasiFile.setFileFilter(filter);
        fileChooserLokasiFile.setFileSelectionMode(fileChooserLokasiFile.DIRECTORIES_ONLY);
        int returnVal = fileChooserLokasiFile.showSaveDialog(this);
        if (returnVal == fileChooserLokasiFile.APPROVE_OPTION) {
            txt_lokasi_db.setText(fileChooserLokasiFile.getSelectedFile() + "\\");
        }
    }//GEN-LAST:event_btnPilihActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
     Process p = null;
        try {
            Runtime runtime = Runtime.getRuntime();
            // Jika MySQL Tanpa Password
            p = runtime.exec("C:/xampp/mysql/bin/mysqldump -uroot --add-drop-database -B " + txt_nama_db.getText() + " -r " 
                    + txt_lokasi_db.getText() + "" + txt_nama_file.getText() + ".sql");
            int processComplete = p.waitFor();
            // screen proses
            if (processComplete == 0) {
                JOptionPane.showMessageDialog(null, "Backup Database Berhasil.");
            } else {
                JOptionPane.showMessageDialog(null, "Backup Database Gagal");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBackupActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new petugas. menuOP().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(backupdata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new backupdata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnPilih;
    private javax.swing.JFileChooser fileChooserLokasiFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_lokasi_db;
    private javax.swing.JTextField txt_nama_db;
    private javax.swing.JTextField txt_nama_file;
    // End of variables declaration//GEN-END:variables
}
